import type { NextPage } from "next";
import Head from "next/head";
import MainContent from "../components/MainContent";
import Sidebar from "../components/Sidebar";

const Home: NextPage = () => {
    return (
        <div className="container mx-auto">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="text-gray-100">
                <Sidebar />
                <MainContent />
            </main>
        </div>
    );
};

export default Home;
